testenv: false
logextrainfo: false
cronfreq: 30s
mailclientconf:
  host: "smtp.gmail.com"
  port: 587
  username: <sender_email_id>
  password: <sender_email_password>
districtconfig:
  token: <telegram_token>
  testchannelconfig:
    - districtid: 395 #mumbai
      agegroup: 18
      channelid: <channelid_of_telegram_group>
  channelconfig:
    - districtid: 395 #mumbai
      agegroup: 18
      channelid: <channelid_of_telegram_group>
    - districtid: 395 #mumbai
      agegroup: 45
      channelid: 5634563234
    - pincode: 400072,400078,400005 #comma separated pincodes
      agegroup: 45
      channelid: 5634563234
pincodeconfig:
  - pincode: 400072,400078,400005,400034 #comma separated pincodes
    agegroup: 18
    email: <email_id_of_receiver>
